"""hh

Revision ID: 725cc9945016
Revises: c6b60d2681f3
Create Date: 2025-01-15 14:56:40.945723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725cc9945016'
down_revision = 'c6b60d2681f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('term_id', sa.INTEGER(), nullable=False),
    sa.Column('grade_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fees')
    # ### end Alembic commands ###
