"""gg

Revision ID: da6e38abc206
Revises: 1e1aa275a41a
Create Date: 2025-01-19 17:08:57.545595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6e38abc206'
down_revision = '1e1aa275a41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_payment_term_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('last_payment_term_id')

    # ### end Alembic commands ###
